package modelos;


import java.util.*;

import modelos.dtos.AnimalDTO;

/**
 * 
 */
public class Animal {

    /**
     * Default constructor
     */
    public Animal() {
    }

    /**
     * 
     */
    private Boolean domestico;

    /**
     * 
     */
    private Float altura;

    /**
     * 
     */
    private Float peso;

    /**
     * 
     */
    private int edad;

    /**
     * 
     */
    private Boolean estadoSaludableAnimal;

    /**
     * 
     */
    private String tipoDeAnimal;

    /**
     * 
     */
    private String nombre;

    /**
     * 
     */
    private String legajo;

    /**
     * 
     */
    private FichaMedica fichaMedica;

}